### ISSUE TITLE
elasticsearch install failed, can you give me some suggests?

### ISSUE THREAD

**Issue by daoxuans** [DynamiteAI/dynamite-nsm#54]
I install just ES like this, failed in passwd?
`[root@venus dynamite_nsm]# dynamite elasticsearch install --es-heap-size=5  --verbose
2020-07-09 20:35:43 DYNAMITE_CMD    INFO       | LOG LEVEL: 10
2020-07-09 20:35:43 DYNAMITE_CMD    INFO       | LOG FILE: /var/log/dynamite/dynamite-09-07-2020.log
[?] Enter the password for logging into ElasticSearch:
[?] Confirm Password:
2020-07-09 20:35:49 ELASTICSEARCH   ERROR      | Could not resolve ES_PATH_CONF environment variable. Is ElasticSearch installed?
/tmp/dynamite/install_cache/elasticsearch-7.2.0.tar.gz
/tmp/dynamite/install_cache/java-11.0.2.tar.gz
useradd: user 'dynamite' already exists
2020-07-09 20:35:59 ELASTICSEARCH   INFO       | Creating ElasticSearch installation, configuration, and logging directories.
2020-07-09 20:35:59 ELASTICSEARCH   DEBUG      | Copying /tmp/dynamite/install_cache/elasticsearch-7.2.0/config/elasticsearch.yml -> /etc/dynamite/elasticsearch/
2020-07-09 20:35:59 ELASTICSEARCH   DEBUG      | Copying /tmp/dynamite/install_cache/elasticsearch-7.2.0/config/jvm.options -> /etc/dynamite/elasticsearch/
2020-07-09 20:35:59 ELASTICSEARCH   DEBUG      | Copying /tmp/dynamite/install_cache/elasticsearch-7.2.0/config/log4j2.properties -> /etc/dynamite/elasticsearch/
2020-07-09 20:35:59 ELASTICSEARCH   DEBUG      | Copying /tmp/dynamite/install_cache/elasticsearch-7.2.0/bin/ -> /opt/dynamite/elasticsearch/bin/
2020-07-09 20:35:59 ELASTICSEARCH   DEBUG      | Copying /tmp/dynamite/install_cache/elasticsearch-7.2.0/lib/ -> /opt/dynamite/elasticsearch/lib/
2020-07-09 20:35:59 ELASTICSEARCH   DEBUG      | Copying /tmp/dynamite/install_cache/elasticsearch-7.2.0/logs/ -> /opt/dynamite/elasticsearch/logs/
2020-07-09 20:35:59 ELASTICSEARCH   DEBUG      | Copying /tmp/dynamite/install_cache/elasticsearch-7.2.0/modules/ -> /opt/dynamite/elasticsearch/modules/
2020-07-09 20:36:00 ELASTICSEARCH   DEBUG      | Copying /tmp/dynamite/install_cache/elasticsearch-7.2.0/plugins/ -> /opt/dynamite/elasticsearch/plugins/
2020-07-09 20:36:00 ELASTICSEARCH   INFO       | Updating ElasticSearch default configuration path [/etc/dynamite/elasticsearch/]
2020-07-09 20:36:00 ELASTICSEARCH   INFO       | Updating ElasticSearch default home path [/opt/dynamite/elasticsearch/]
2020-07-09 20:36:00 ELASTICSEARCH   INFO       | Overwriting default configuration.
2020-07-09 20:36:00 ELASTICSEARCH   INFO       | Setting up JVM default heap settings [5GB]
2020-07-09 20:36:00 ELASTICSEARCH   INFO       | Setting up Max File Handles [65535] VM Max Map Count [262144]
vm.max_map_count = 262144
fs.file-max = 65535
fs.inotify.max_user_watches = 524288
vm.max_map_count = 262144
fs.file-max = 65535
2020-07-09 20:36:00 ELASTICSEARCH   INFO       | Creating certificate keystore.
2020-07-09 20:36:17 ELASTICSEARCH   WARNING    | An issue occurred while attempting to start.
2020-07-09 20:36:21 ELASTICSEARCH   WARNING    | An issue occurred while attempting to start.
2020-07-09 20:36:24 ELASTICSEARCH   WARNING    | An issue occurred while attempting to start.
2020-07-09 20:36:27 ELASTICSEARCH   WARNING    | An issue occurred while attempting to start.
2020-07-09 20:36:30 ELASTICSEARCH   WARNING    | An issue occurred while attempting to start.
2020-07-09 20:36:33 ELASTICSEARCH   INFO       | [Attempt: 6] Starting ElasticSearch on PID [19952]
2020-07-09 20:36:33 ELASTICSEARCH   INFO       | Waiting for ElasticSearch API to become accessible.
2020-07-09 20:36:38 ELASTICSEARCH   INFO       | Waiting for ElasticSearch API to become accessible.
2020-07-09 20:36:43 ELASTICSEARCH   INFO       | Waiting for ElasticSearch API to become accessible.
2020-07-09 20:36:48 ELASTICSEARCH   INFO       | Waiting for ElasticSearch API to become accessible.
2020-07-09 20:36:53 ELASTICSEARCH   INFO       | ElasticSearch API is up.
2020-07-09 20:36:58 ELASTICSEARCH   INFO       | Bootstrapping passwords.
2020-07-09 20:37:11 ELASTICSEARCH   DEBUG      | Updating password for apm_system
2020-07-09 20:37:11 ELASTICSEARCH   DEBUG      | Fallback; encoding bytes to utf-8 charset before building b64 auth package.
2020-07-09 20:37:11 ELASTICSEARCH   DEBUG      | Fallback; encoding bytes to utf-8 charset making request.
2020-07-09 20:37:11 ELASTICSEARCH   ERROR      | General exception while resetting Elasticsearch password.
2020-07-09 20:37:11 ELASTICSEARCH   DEBUG      | General exception while resetting Elasticsearch password; Remote end closed connection without response
2020-07-09 20:37:11 ELASTICSEARCH   ERROR      | Failed to bootstrap password.
2020-07-09 20:37:11 ELASTICSEARCH   ERROR      | General error occurred while attempting to bootstrap ElasticSearch passwords.
2020-07-09 20:37:11 ELASTICSEARCH   DEBUG      | General error occurred while attempting to bootstrap ElasticSearch passwords An error occurred while attempting to install component: An error occurred while installing elasticsearch: Failed to bootstrap password.
2020-07-09 20:37:11 DYNAMITE_CMD    CRITICAL   | Fatal error. Exiting.
2020-07-09 20:37:11 DYNAMITE_CMD    DEBUG      | Fatal error. Exiting; An error occurred while attempting to install component: An error occurred while installing elasticsearch: General error occurred while attempting to bootstrap ElasticSearch passwords An error occurred while attempting to install component: An error occurred while installing elasticsearch: Failed to bootstrap password.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/dynamite_nsm/services/elasticsearch/config.py", line 310, in _set_user_password
    urlopen(url_request)
  File "/usr/lib64/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 524, in open
    req = meth(req)
  File "/usr/lib64/python3.6/urllib/request.py", line 1248, in do_request_
    raise TypeError(msg)
TypeError: POST data should be bytes, an iterable of bytes, or a file object. It cannot be of type str.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/dynamite_nsm/services/elasticsearch/config.py", line 313, in _set_user_password
    urlopen(url_request, data=json.dumps({'password': password}).encode('utf-8'))
  File "/usr/lib64/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib64/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/lib64/python3.6/urllib/request.py", line 1321, in do_open
    r = h.getresponse()
  File "/usr/lib64/python3.6/http/client.py", line 1346, in getresponse
    response.begin()
  File "/usr/lib64/python3.6/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.6/http/client.py", line 276, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/dynamite_nsm/services/elasticsearch/install.py", line 353, in setup_passwords
    setup_from_bootstrap(bootstrap_p_res[0].decode())
  File "/usr/local/lib/python3.6/site-packages/dynamite_nsm/services/elasticsearch/install.py", line 285, in setup_from_bootstrap
    es_pass_config.set_all_passwords(new_password=self.password)
  File "/usr/local/lib/python3.6/site-packages/dynamite_nsm/services/elasticsearch/config.py", line 392, in set_all_passwords
    self.set_apm_system_password(new_password)
  File "/usr/local/lib/python3.6/site-packages/dynamite_nsm/services/elasticsearch/config.py", line 338, in set_apm_system_password
    self._set_user_password('apm_system', new_password)
  File "/usr/local/lib/python3.6/site-packages/dynamite_nsm/services/elasticsearch/config.py", line 329, in _set_user_password
    "General exception while resetting Elasticsearch password; {}".format(e))
dynamite_nsm.exceptions.ResetPasswordError: An error occurred while attempting to reset password: General exception while resetting Elasticsearch password; Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/dynamite_nsm/services/elasticsearch/install.py", line 358, in setup_passwords
    raise elastic_exceptions.InstallElasticsearchError("Failed to bootstrap password.")
dynamite_nsm.services.elasticsearch.exceptions.InstallElasticsearchError: An error occurred while attempting to install component: An error occurred while installing elasticsearch: Failed to bootstrap password.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/dynamite", line 88, in <module>
    ElasticsearchCommandlineComponent(args)
  File "/usr/local/lib/python3.6/site-packages/dynamite_nsm/components/elasticsearch/component.py", line 103, in __init__
    self.execute_install_strategy()
  File "/usr/local/lib/python3.6/site-packages/dynamite_nsm/components/base/component.py", line 63, in execute_strategy_function
    self.execute_strategy(self.component_name, strategy)
  File "/usr/local/lib/python3.6/site-packages/dynamite_nsm/components/base/component.py", line 82, in execute_strategy
    strategy.execute_strategy()
  File "/usr/local/lib/python3.6/site-packages/dynamite_nsm/components/base/execution_strategy.py", line 51, in execute_strategy
    func(**args)
  File "/usr/local/lib/python3.6/site-packages/dynamite_nsm/services/elasticsearch/install.py", line 416, in install_elasticsearch
    es_installer.setup_elasticsearch()
  File "/usr/local/lib/python3.6/site-packages/dynamite_nsm/services/elasticsearch/install.py", line 266, in setup_elasticsearch
    self.setup_passwords()
  File "/usr/local/lib/python3.6/site-packages/dynamite_nsm/services/elasticsearch/install.py", line 364, in setup_passwords
    "General error occurred while attempting to bootstrap ElasticSearch passwords {}".format(e))
dynamite_nsm.services.elasticsearch.exceptions.InstallElasticsearchError: An error occurred while attempting to install component: An error occurred while installing elasticsearch: General error occurred while attempting to bootstrap ElasticSearch passwords An error occurred while attempting to install component: An error occurred while installing elasticsearch: Failed to bootstrap password.
`

**Comment by JaminB** [comment]
Interesting, I'll attempt to duplicate on this side. In the meantime, try upgrading to `python3 and pip3`. This looks like a python2.7 specific issue, that should have been addressed by some fallback methods, but those seem to be failing.
